require "src/core/cocos_ext/CNode"
require "src/core/cocos_ext/CLayer"
require "src/core/cocos_ext/CScene"
require "src/core/cocos_ext/CRichText"
require "src/core/cocos_ext/CImageView"
require "src/core/cocos_ext/CListView"
require "src/core/cocos_ext/CScrollView"
